### ISSUE TITLE
Normalize extension implementations to follow best practices

### ISSUE THREAD

**Issue by gadomski** [stac-utils/pystac#1228]
Extensions use differerent patterns and may not be fully correct -- we should make sure all extensions in this repo are up to the latest best practices.

## Tasks

- [x] Build the extensions list below
- [x] Define "best practices"
- [x] Audit each extension
- [ ] Close all issues for specific extension versions (noted below)

## Best practices

- Includes tests for all published versions
- Implements migration for all v1-and-beyond versions

## Extensions list

- [x] Classification
  - [x] v1.0.0
  - [x] v1.1.0
- [x] Datacube
  - [x] v1.0.0
  - [x] v2.0.0
  - [x] v2.1.0: https://github.com/stac-utils/pystac/issues/856
  - [x] v2.2.0: https://github.com/stac-utils/pystac/issues/856
- [x] Eo
  - [x] v1.0.0
  - [x] v1.1.0
- [x] File
  - [x] v1.0.0: https://github.com/stac-utils/pystac/issues/472 
  - [x] v2.0.0
  - [x] v2.1.0: https://github.com/stac-utils/pystac/issues/1247
- [x] Grid
  - [x] v1.0.0
  - [x] v1.1.0
- [x] Item Assets
  - [x] v1.0.0
- [x] Label: https://github.com/stac-utils/pystac/issues/1249
  - [x] v1.0.0
  - [x] v1.0.1
- [x] Mgrs
  - [x] v1.0.0
- [x] Pointcloud
  - [x] v1.0.0
- [x] Projection
  - [x] v1.0.0
  - [x] v1.1.0
- [x] Raster
  - [x] v1.0.0
  - [x] v1.1.0
- [x] Sar
  - [x] v1.0.0
- [x] Sat
  - [x] v1.0.0
- [x] Scientific
  - [x] v1.0.0
- [x] Storage
  - [x] v1.0.0
- [x] Table
  - [x] v1.0.0
  - [x] v1.0.1
  - [x] v1.1.0
  - [x] v1.2.0
- [x] Timestamps
  - [x] v1.0.0
  - [x] v1.1.0
- [x] Version
  - [x] v1.0.0
  - [x] v1.1.0: https://github.com/stac-utils/pystac/issues/1257
  - [x] v1.2.0: https://github.com/stac-utils/pystac/issues/1257
- [x] View
  - [x] v1.0.0
- [x] Xarray Assets
  - [x] v1.0.0

**Comment by gadomski** [comment]
@jsignell no rush, but if you have more "best practices" that you've noticed (or that you notice while working on other tickets), can you add them to the list?

**Comment by jsignell** [comment]
I think this one is good to close! I just checked the last todo items that were associated with merge PRs
